-- phpMyAdmin SQL Dump
-- version 4.7.7
-- https://www.phpmyadmin.net/
--
-- Хост: 127.0.0.1:3306
-- Время создания: Июл 21 2018 г., 20:11
-- Версия сервера: 5.6.38
-- Версия PHP: 5.5.38

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- База данных: `csv`
--

-- --------------------------------------------------------

--
-- Структура таблицы `csvFile`
--

CREATE TABLE `csvFile` (
  `site` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `name` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `country` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `enrollment` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `curriculum` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `school_year` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `foundation_date` int(10) DEFAULT NULL,
  `averege_class_size` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `clubs` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Дамп данных таблицы `csvFile`
--

INSERT INTO `csvFile` (`site`, `name`, `country`, `enrollment`, `curriculum`, `school_year`, `foundation_date`, `averege_class_size`, `clubs`) VALUES
('None', 'None', 'None', 'None', 'None', 'None', 0, 'None', 'None'),
('http://www.actirana.edu.al', 'Albanian College', 'Albania', '700 Students PreK-12', 'International, International Baccalaureate Diploma (IB Diploma), International Baccalaureate Middle Years Programme (IBMYP), International Baccalaureate Primary Years Programme (IBPYP)', 'September - June', 2015, 'Elementary: 15, Secondary: 15', 'None'),
('http://https://www.qsi.org/albania/alb', 'QSI Tirana International School', 'Albania', '205 Students PreK-12', 'Advanced Placement (AP), United States', 'August - June', 1991, 'Elementary: 15, Secondary: 10', 'None'),
('http://www.qsi.org/arm', 'QSI International School of Yerevan', 'Armenia', '147 Students PreK-12', 'Advanced Placement (AP), United States', 'August - June', 1995, 'Elementary: 11, Secondary: 8', 'Running, Chess, Martial Arts, Ballet, Drama, Choir, Running, Math'),
('http://www.ais-salzburg.at', 'American International School Salzburg', 'Austria', '86 Students 7-13', 'Advanced Placement (AP), United States', 'September - May', 1977, 'Secondary: 7', 'None'),
('http://www.ais.at', 'American International School Vienna', 'Austria', '780 Students PreK-12', 'Advanced Placement (AP), International Baccalaureate Diploma (IB Diploma), United States, Austrian Matura Equivalency', 'August - June', 1959, 'Elementary: 20, Secondary: 18', 'None'),
('http://www.stgis.at', 'St. Gilgen International School', 'Austria', '4-12', 'International, International Baccalaureate Diploma (IB Diploma)', 'September - June', 2008, 'Secondary: 10', 'Orienteering, Snow Sports, Rock Climbing, Chess, Arts & Crafts, Songwriting'),
('http://www.vis.ac.at', 'Vienna International School', 'Austria', '1,438 Students PreK-12', 'International Baccalaureate Diploma (IB Diploma), International Baccalaureate Middle Years Programme (IBMYP), International Baccalaureate Primary Years Programme (IBPYP)', 'August - June', 1978, 'Elementary: 20, Secondary: 22', 'Math, Science, Girl/Boy Scouts'),
('None', 'None', 'None', 'None', 'None', 'None', 0, 'None', 'None'),
('http://www.qsi.org/schoolpages/azb/home', 'QSI Baku International School', 'Azerbaijan', '219 Students PreK-12', 'Advanced Placement (AP), United States', 'August - June', 1994, 'Elementary: 16, Secondary: 10', 'Student Council, National Honor Society, Gymnastics, Ballet, Arts & Crafts, Chess,  Instrumental Mus'),
('http://www.tisa.az', 'The International School of Azerbaijan', 'Azerbaijan', '613 Students Nursery-12', 'International Baccalaureate Diploma (IB Diploma), International Baccalaureate Middle Years Programme (IBMYP), International Baccalaureate Primary Years Programme (IBPYP)', 'August - June', 1996, 'Elementary: 16, Secondary: 12', 'None'),
('http://minsk.qsischool.org', 'QSI International School of Minsk', 'Belarus', '155 Students PreK-12', 'Advanced Placement (AP), United States', 'August - June', 1993, 'Elementary: 12, Secondary: 7', 'Chess, Yearbook, Student Council, Russian, Photography, Various Sports, Community Service'),
('http://www.ais-antwerp.be', 'Antwerp International School, vzw', 'Belgium', '403 Students Nursery-12', 'International, International Baccalaureate Diploma (IB Diploma), International Baccalaureate Middle Years Programme (IBMYP), International Baccalaureate Primary Years Programme (IBPYP)', 'August - June', 1967, 'Elementary: 16, Secondary: 18', 'None'),
('http://www.beps.com', 'BEPS International School', 'Belgium', '193 Students N-8', 'International, IPC, United Kingdom', 'September - June', 1972, 'Elementary: 16', 'None'),
('http://', 'Bogaerts International School', 'Belgium', 'Nursery-12', 'International Baccalaureate Diploma (IB Diploma), International Baccalaureate Middle Years Programme (IBMYP), International Baccalaureate Primary Years Programme (IBPYP), United Kingdom', 'September - June', 2012, 'Elementary: 15, Secondary: 15', 'None'),
('http://www.stjohns.be', 'St. John\'s International School', 'Belgium', '809 Students Nursery-12', 'Advanced Placement (AP), International, International Baccalaureate Diploma (IB Diploma), International Baccalaureate Primary Years Programme (IBPYP)', 'August - June', 1964, 'Elementary: 16, Secondary: 18', 'Chess, Ceramics, Math, Science, Drama, Dance, Sports'),
('http://www.stpaulsbps.com', 'St. Paul\'s British Primary School', 'Belgium', '80 Students N-6', 'United Kingdom', 'September - July', 1975, 'Elementary: 12', 'None'),
('http://www.bisb.org', 'The British International School of Brussels', 'Belgium', '130 Students Nursery-5', 'United Kingdom', 'September - June', 2000, 'Elementary: 16', 'Computers, Book Making, Drama, Needlework, Soccer, Jazz Ballet, Origami, Karate, Chess'),
('http://www.isb.be', 'The International School of Brussels', 'Belgium', '1,535 Students Nursery-13', 'International, International Baccalaureate Diploma (IB Diploma), United States', 'August - June', 1951, 'Elementary: 22, Secondary: 18', 'None'),
('http://https://www.qsi.org/bosnia-and-herzegovina/bhz/', 'QSI International School of Sarajevo', 'Bosnia and Herzegovina', '125 Students PreK-12', 'Advanced Placement (AP), United States', 'August - June', 1997, 'Elementary: 12, Secondary: 8', 'Roots & Shoots, Student Council, Model United Nations, National Honor Society'),
('http://', 'American English Academy (An ISS-Managed School)', 'Bulgaria', 'K-12', 'Advanced Placement (AP), International, National, United States', 'September - July', 1992, 'Elementary: 20, Secondary: 12', 'Chess Club, Classical Guitar Club'),
('http://www.aas-sofia.org', 'Anglo-American School of Sofia', 'Bulgaria', '530 Students PreK-12', 'International Baccalaureate Diploma (IB Diploma), United Kingdom, United States, US Common Core (literacy & numeracy), European Framework (world languages)', 'August - June', 1967, 'Elementary: 20, Secondary: 18', 'Mathcounts, Robotics, Cultural Studies, Choir, Composting, Human Rights'),
('http://www.acs.bg', 'The American College of Sofia', 'Bulgaria', '806 Students 8-12', 'International Baccalaureate Diploma (IB Diploma), National, United States', 'September - June', 1860, 'Secondary: 18', 'None'),
('http://www.aisz.hr', 'American International School of Zagreb', 'Croatia', '256 Students PreK-12', 'International, International Baccalaureate Diploma (IB Diploma), United States', 'August - June', 1966, 'Elementary: 16, Secondary: 18', 'Chess, Knowledge Bowl, MathCounts, Science Explorers'),
('http://www.aisc.ac.cy', 'The American International School in Cyprus', 'Cyprus', '225 Students PreK-12', 'International Baccalaureate Diploma (IB Diploma), United States', 'August - June', 1987, 'Elementary: 15, Secondary: 12', 'Choir, Jewelry, Crafts, Math Support, Basketball, Ceramics, School Band, Robotics, Cultural Activiti'),
('http://www.isp.cz', 'International School of Prague s.r.o.', 'Czech Republic', '896 Students PreK-12', 'International, International Baccalaureate Diploma (IB Diploma)', 'August - June', 1948, 'Elementary: 20, Secondary: 20', 'Student Leadership, Knowledge Bowl, MathCounts, Korean, Vietnam'),
('None', 'None', 'None', 'None', 'None', 'None', 0, 'None', 'None'),
('http://www.cis.dk', 'Copenhagen International School', 'Denmark', '930 Students PreK-12', 'International Baccalaureate Diploma (IB Diploma), International Baccalaureate Middle Years Programme (IBMYP), International Baccalaureate Primary Years Programme (IBPYP)', 'August - June', 1963, 'Elementary: 22, Secondary: 18', 'None'),
('http://www.ise.edu.ee', 'International School of Estonia', 'Estonia', '133 Students PreK-12', 'International, International Baccalaureate Diploma (IB Diploma), International Baccalaureate Primary Years Programme (IBPYP), International Baccalaureate Middle Years Programme (IBMYP)', 'August - June', 1995, 'Elementary: 9, Secondary: 11', 'Art, Dance, Homework, IT, Archery, Singing, Tap Dance'),
('http://www.ish.edu.hel.fi', 'International School of Helsinki', 'Finland', '359 Students PreK-12', 'International Baccalaureate Diploma (IB Diploma), International Baccalaureate Middle Years Programme (IBMYP), International Baccalaureate Primary Years Programme (IBPYP)', 'August - June', 1963, 'Elementary: 16, Secondary: 16', 'Sports, Arts, Drama, Media, Music, Dance'),
('http://www.eschool.edu.hel.fi/', 'The English School', 'Finland', 'K-12', 'International General Certificate of Secondary Education(IGCSE), United Kingdom, United States, National Finnish curriculum', 'August - June', 1945, 'Elementary: 25, Secondary: 20', 'None'),
('http://www.asparis.org', 'American School of Paris', 'France', '750 Students N-13', 'Advanced Placement (AP), International Baccalaureate Diploma (IB Diploma), United States', 'August - June', 1946, 'Elementary: 19, Secondary: 18', 'National Honor Society, Habitat for Humanity, Romania Children\'s Relief, Kalahari Experience, Sumba'),
('http://www.bordeaux-school.com', 'Bordeaux International School', 'France', '150 Students Nursery-13', 'International, International General Certificate of Secondary Education(IGCSE), National', 'September - June', 1987, 'Elementary: 12-14, Secondary: 8-12', 'French, Robotics, Drama, Music Band'),
('http://www.isn-nice.com', 'International School of Nice', 'France', '347 Students PreK-12', 'International, International Baccalaureate Diploma (IB Diploma), International Baccalaureate Primary Years Programme (IBPYP), International General Certificate of Secondary Education(IGCSE)', 'September - June', 1977, 'Elementary: 22, Secondary: 22', 'MUN, Drama, Art,'),
('http://www.isparis.edu', 'International School of Paris', 'France', '688 Students Nursery-12', 'International, International Baccalaureate Diploma (IB Diploma), International Baccalaureate Middle Years Programme (IBMYP), International Baccalaureate Primary Years Programme (IBPYP)', 'September - June', 1964, 'Elementary: 17, Secondary: 13', 'Student Council, Student Tech Team, Sustainable Development Project'),
('http://www.marymount.fr', 'Marymount International School, Paris', 'France', 'N-8', 'United States', 'September - June', 1923, 'Elementary: 18, Secondary: 17', 'Kumon Math, Art, Make A Difference'),
('http://www.sya.org', 'School Year Abroad (SYA) -  France', 'France', '65 Students 11-12', 'Advanced Placement (AP), United States, DELF for language', 'September - June', 1965, 'Secondary: 10-12', 'None'),
('http://tbilisi.qsi.org', 'QSI International School of Tbilisi', 'Georgia', '253 Students Nursery-12', 'Advanced Placement (AP), United States', 'August - June', 1995, 'Elementary: 12-18, Secondary: 12-15', 'MUN, JMUN, Speech & Debate, Community Service Club, National Honor Society'),
('http://www.bis-school.com', 'Bavarian International School gAG', 'Germany', '1,028 Students PreK-12', 'International Baccalaureate Diploma (IB Diploma), International Baccalaureate Middle Years Programme (IBMYP), International Baccalaureate Primary Years Programme (IBPYP), Mittlere Reife', 'August - June', 1991, 'Elementary: 24, Secondary: 24', 'Drama'),
('http://www.bbis.de', 'BBIS Berlin Brandenburg International School GmbH', 'Germany', '703 Students K-12', 'International, International Baccalaureate Diploma (IB Diploma), International Baccalaureate Middle Years Programme (IBMYP), International Baccalaureate Primary Years Programme (IBPYP), IBCC', 'August - June', 1990, 'Elementary: 16, Secondary: 16', 'Drama, Sailing, Human Rights, Dancing, Junior Math, Senior Math, Chess, German'),
('http://www.berlin-international-school.de', 'Berlin International School', 'Germany', '820 Students 1-12', 'International Baccalaureate Diploma (IB Diploma), International Baccalaureate Primary Years Programme (IBPYP), International General Certificate of Secondary Education(IGCSE), National, United States', 'August - July', 1998, 'Elementary: 24, Secondary: 21', 'Extensive after school activities program'),
('http://www.bonn-is.de', 'Bonn International School', 'Germany', '745 Students PreK-12', 'International Baccalaureate Diploma (IB Diploma), International Baccalaureate Middle Years Programme (IBMYP), International Baccalaureate Primary Years Programme (IBPYP)', 'August - June', 1997, 'Elementary: 18, Secondary: 16', 'Dance, Musical Theatre, Running'),
('http://www.dresden-is.de', 'Dresden International School', 'Germany', '506 Students Nursery-12', 'International Baccalaureate Diploma (IB Diploma), International Baccalaureate Middle Years Programme (IBMYP), International Baccalaureate Primary Years Programme (IBPYP), United States', 'August - June', 1996, 'Elementary: 15, Secondary: 17', 'Sports, Yearbook, Aerobics, Yoga, Dutch, Student Ambassador Program, Russian, Knitting, Photography,'),
('http://www.fis.edu', 'Frankfurt International School', 'Germany', '1,817 Students Nursery-12', 'International Baccalaureate Diploma (IB Diploma), International Baccalaureate Primary Years Programme (IBPYP)', 'August - June', 1961, 'Elementary: 20, Secondary: 20', 'Booster'),
('http://www.is-hr.de', 'International School Hannover Region', 'Germany', '550 Students PreK-12', 'International Baccalaureate Diploma (IB Diploma), International Baccalaureate Middle Years Programme (IBMYP), International Baccalaureate Primary Years Programme (IBPYP)', 'August - June', 1996, 'Elementary: 18, Secondary: 18', 'Choir, Media'),
('http://www.isbremen.de', 'International School of Bremen', 'Germany', '368 Students Nursery-12', 'International, International Baccalaureate Diploma (IB Diploma), International General Certificate of Secondary Education(IGCSE), IMYC, IPC', 'August - June', 1998, 'Elementary: 18, Secondary: 16', 'Key Club'),
('http://www.ishamburg.org', 'International School of Hamburg', 'Germany', '779 Students N-12', 'International Baccalaureate Diploma (IB Diploma), International Baccalaureate Middle Years Programme (IBMYP), IPC', 'August - June', 1957, 'Elementary: 20, Secondary: 18', 'None'),
('http://www.international-school-stuttgart.de', 'International School of Stuttgart', 'Germany', '824 Students PreK-12', 'International, International Baccalaureate Diploma (IB Diploma), International Baccalaureate Middle Years Programme (IBMYP), International Baccalaureate Primary Years Programme (IBPYP)', 'August - July', 1985, 'Elementary: 22, Secondary: 22', 'International Award'),
('http://www.is-ulm.de', 'International School of Ulm/Neu-Ulm', 'Germany', '190 Students PreK-12', 'International, International Baccalaureate Diploma (IB Diploma), International Baccalaureate Primary Years Programme (IBPYP), International General Certificate of Secondary Education(IGCSE), United Kingdom, United States', 'August - June', 2005, 'Elementary: 16, Secondary: 10', 'None'),
('http://www.isf-sabis.net', 'ISF International School Frankfurt Rhein-Main', 'Germany', '783 Students PreK-12', 'Advanced Placement (AP), International Baccalaureate Diploma (IB Diploma), SABIS(R)', 'August - June', 1995, 'Elementary: 25, Secondary: 20', 'None'),
('http://www.jfks.de', 'John F. Kennedy School Berlin', 'Germany', '1,700 Students K-12', 'Advanced Placement (AP), National, United States', 'August - July', 1960, 'Elementary: 18 to 21, Secondary: 18', 'None'),
('http://www.intschool-leipzig.com', 'Leipzig International School', 'Germany', '859 Students N-12', 'International, International Baccalaureate Diploma (IB Diploma), International General Certificate of Secondary Education(IGCSE)', 'August - July', 1992, 'Elementary: 20, Secondary: 20', 'None'),
('http://www.mis-munich.de', 'Munich International School', 'Germany', '1,273 Students PreK-12', 'General Certificate of Secondary Education (GCSE), International Baccalaureate Diploma (IB Diploma), International Baccalaureate Middle Years Programme (IBMYP), International Baccalaureate Primary Years Programme (IBPYP), International General Certificate', 'August - June', 1966, 'Elementary: 20, Secondary: 20', 'Languages'),
('http://www.acs.gr', 'ACS Athens (American Community Schools)', 'Greece', '976 Students PreK-12', 'Advanced Placement (AP), International Baccalaureate Diploma (IB Diploma), United States', 'September - June', 1945, 'Elementary: 19.6, Secondary: 16.9', 'Forensics, Model UN, Current Events/Leadership, Math, Recycling, Environmental, Science, French, Ger'),
('http://www.isa.edu.gr', 'International School of Athens', 'Greece', '410 Students N-12', 'International Baccalaureate Diploma (IB Diploma), International Baccalaureate Middle Years Programme (IBMYP), International Baccalaureate Primary Years Programme (IBPYP), United States', 'September - June', 1972, 'Elementary: 15, Secondary: 15', 'Dance, Arts & Crafts, Cinema, Band, Guitar, Bowling, Chinese, Russian, Martial Arts, Photography, Pi'),
('http://www.pinewood.gr', 'Pinewood - American International School of Thessaloniki', 'Greece', '290 Students PreK-12', 'International Baccalaureate Diploma (IB Diploma), United States', 'September - June', 1950, 'Elementary: 15, Secondary: 15', 'Forensics'),
('http://www.aisb.hu', 'American International School of Budapest', 'Hungary', '877 Students PreK-12', 'International, International Baccalaureate Diploma (IB Diploma), United States', 'August - June', 1973, 'Elementary: 16, Secondary: 14', 'National Honor Society, Community Service, MathCounts, Sports'),
('http://www.st-andrews.ie', 'St. Andrew\'s College', 'Ireland', '1,125 Students K-12', 'International Baccalaureate Diploma (IB Diploma), National', 'August - June', 1894, 'Elementary: 21, Secondary: 24', 'Book, Computer, Gaelach, Board Game, Christian Union, Debating Society'),
('http://www.suttonparkschool.com', 'Sutton Park School', 'Ireland', 'K-13', 'National, Irish Department of Education & Science Curriculum', 'September - June', 1957, 'Elementary: 21, Secondary: 22', 'None'),
('http://www.aosr.org', 'American Overseas School of Rome', 'Italy', '626 Students PreK-12', 'Advanced Placement (AP), International Baccalaureate Diploma (IB Diploma), National, United States', 'September - June', 1947, 'Elementary: 18, Secondary: 18', 'Environmental \"\"Go Green\"\"'),
('http://www.asmilan.org', 'American School of Milan', 'Italy', '791 Students N-12', 'International Baccalaureate Diploma (IB Diploma), United States', 'September - June', 1962, 'Elementary: 18, Secondary: 22', 'NHS, Junior NHS, Student Government, Student STEAM'),
('http://www.iscomo.com', 'International School of Como', 'Italy', '290 Students PreK-8', 'International Baccalaureate Middle Years Programme (IBMYP), International Baccalaureate Primary Years Programme (IBPYP)', 'September - June', 2002, 'Elementary: 20, Secondary: 14', 'None'),
('http://www.isfitaly.org', 'International School of Florence', 'Italy', '461 Students N-12', 'International Baccalaureate Diploma (IB Diploma), International Baccalaureate Primary Years Programme (IBPYP)', 'September - June', 1952, 'Elementary: 16, Secondary: 16', 'Yearbook, Art, Drama, Music, soccer, Volleyball, choir'),
('http://www.ism-ac.it', 'International School of Milan', 'Italy', '960 Students Nursery-12', 'International, International Baccalaureate Diploma (IB Diploma), International Baccalaureate Middle Years Programme (IBMYP), International Baccalaureate Primary Years Programme (IBPYP)', 'September - June', 1958, 'Elementary: 22, Secondary: 15', 'None'),
('http://www.istrieste.org', 'International School of Trieste', 'Italy', '350 Students Nursery-13', 'Advanced Placement (AP), International, United States', 'September - June', 1964, 'Elementary: 23, Secondary: 18', 'None'),
('http://www.isturin.it', 'International School of Turin', 'Italy', '461 Students Nursery-12', 'International Baccalaureate Diploma (IB Diploma), International Baccalaureate Middle Years Programme (IBMYP), International Baccalaureate Primary Years Programme (IBPYP), National', 'September - June', 1963, 'Elementary: 20, Secondary: 20', 'Photography, Drama,  Art, Choir'),
('http://www.marymountrome.org', 'Marymount International School Rome', 'Italy', '648 Students PreK-12', 'International, International Baccalaureate Diploma (IB Diploma), National, United States', 'September - June', 1946, 'Elementary: 18, Secondary: 15', 'Chess, National Honor Society, Environmental, Student Council, Varsity Sports, International, Studen'),
('None', 'None', 'None', 'None', 'None', 'None', 0, 'None', 'None'),
('http://brindisi.qsischool.org', 'QSI International School of Brindisi', 'Italy', '45 Students PreK-12', 'Advanced Placement (AP), United States', 'August - June', 2005, 'Elementary: 8, Secondary: 4', 'Math, Robotics, Studio Art, Drama'),
('http://www.sssrome.it', 'St. Stephen\'s School', 'Italy', '295 Students 9-13', 'Advanced Placement (AP), International, International Baccalaureate Diploma (IB Diploma), United States', 'September - June', 1964, 'Secondary: 13', 'Debate Club, Italian, Down Syndrome, Theater, Reach Out, Recycling, Students United for Nature, Soup'),
('http://www.eisp.it', 'The English International School of Padua', 'Italy', '760 Students N-12', 'International Baccalaureate Diploma (IB Diploma), International General Certificate of Secondary Education(IGCSE), National, United Kingdom', 'September - June', 1987, 'Elementary: 20, Secondary: 20', 'None'),
('http://www.aisge.it', 'The International School in Genoa', 'Italy', '405 Students N-12', 'International, International Baccalaureate Diploma (IB Diploma), IPC, United States', 'September - June', 1966, 'Elementary: 19, Secondary: 15', 'Elementary Musical, Middle & High School Musical'),
('http://www.isnaples.it', 'The International School of Naples', 'Italy', '231 Students PreK-12', 'National, United States', 'September - June', 1964, 'Elementary: 20, Secondary: 25', 'Student Council, Drama, Arts & Crafts, Guitar, Piano'),
('http://www.udineis.org', 'The Udine International School', 'Italy', '250 Students N-8', 'International, National, United Kingdom, United States', 'September - June', 2003, 'Elementary: 20, Secondary: 17', 'Drama, Homework, Italian Reading, Fitness, Soccer'),
('http://www.uwcad.it', 'United World College of the Adriatic', 'Italy', '12-13', 'International Baccalaureate Diploma (IB Diploma)', 'September - May', 1982, 'Secondary: 15', 'None'),
('http://www.isl.edu.lv', 'International School of Latvia', 'Latvia', '364 Students PreK-12', 'International Baccalaureate Diploma (IB Diploma), International Baccalaureate Middle Years Programme (IBMYP), International Baccalaureate Primary Years Programme (IBPYP)', 'August - June', 1994, 'Elementary: 20, Secondary: 20', 'None'),
('http://www.aisv.lt', 'American International School of Vilnius', 'Lithuania', '243 Students PreK-12', 'International Baccalaureate Diploma (IB Diploma), United States', 'August - June', 1993, 'Elementary: 15, Secondary: 12', 'None'),
('http://', 'Vilnius International School', 'Lithuania', '403 Students PreK-12', 'International Baccalaureate Middle Years Programme (IBMYP), International Baccalaureate Primary Years Programme (IBPYP)', 'September - June', 2004, 'Elementary: 19, Secondary: 15', 'None'),
('http://www.islux.lu', 'International School of Luxembourg', 'Luxembourg', '1,360 Students PreK-12', 'International, International Baccalaureate Diploma (IB Diploma), International General Certificate of Secondary Education(IGCSE)', 'August - June', 1963, 'Elementary: 18, Secondary: 18', 'Duke of Edinburgh\'s Award, Student Council, Choir, Band, Yearbook, Debate, Business'),
('http://www.asm.edu.mk', 'American School Macedonia', 'Macedonia', '110 Students PreK-12', 'Advanced Placement (AP), United States, Macedonian Secondary', 'September - June', 1994, 'Elementary: 8, Secondary: 8', 'None'),
('http://skopje.qsischool.org', 'QSI International School of Skopje', 'Macedonia', '67 Students PreK-12', 'Advanced Placement (AP), United States', 'August - June', 1996, 'Elementary: 9, Secondary: 3', 'Science, Scouting, Soccer, Computer'),
('http://www.qsimalta.org', 'QSI International School of Malta', 'Malta', '158 Students PreK-12', 'Advanced Placement (AP), United States', 'August - June', 2007, 'Elementary: 10, Secondary: 13', 'None'),
('http://chisinau.qsischool.org', 'QSI International School of Chisinau', 'Moldova', '88 Students Nursery-12', 'Advanced Placement (AP), United States', 'August - June', 1996, 'Elementary: 10, Secondary: 6', 'Book, Chess, Creative Dance, Poetry, Drama, Math, Cooking'),
('http://www.qsi.org/montenegro/mtg', 'QSI International School of Montenegro', 'Montenegro', '73 Students PreK-12', 'Advanced Placement (AP), International, United States', 'August - June', 2006, 'Elementary: 12, Secondary: 5', 'Tennis, Soccer, Math/Science,  Coding, Marksmanship, Martial Arts, Salsa, Karaoke, Cross-country run'),
('http://www.afnorth-is.com', 'AFNORTH International School', 'Netherlands', 'PreK-12', 'United States, United Kingdom, Advanced Placement (AP), Hauptschule, Realschule, Ontario Secondary Diploma', 'August - June', 1967, 'Elementary: 20, Secondary: 20', 'International, National Honor Society, Junior Honor Society'),
('http://www.aisr.nl', 'American International School of Rotterdam', 'Netherlands', '250 Students PreK-12', 'International Baccalaureate Diploma (IB Diploma), IMYC, IPC, United States', 'August - June', 1959, 'Elementary: 18, Secondary: 10', 'Mini Sharks Soccer, Music, Drama, Computer Programming, Art'),
('http://www.ash.nl', 'American School of The Hague', 'Netherlands', '1,239 Students N-13', 'Advanced Placement (AP), International, International Baccalaureate Diploma (IB Diploma), United States', 'August - June', 1953, 'Elementary: 18, Secondary: 18', 'Role Playing, Chess, Math, Jazz Band, Speech & Debate, Student Senate, Online Art Forum, Service Lea'),
('http://www.eerde.nl', 'International School Eerde', 'Netherlands', '77 Students K-13', 'International Baccalaureate Diploma (IB Diploma), International General Certificate of Secondary Education(IGCSE), Cambridge Secondary 1', 'August - July', 1934, 'Elementary: 7, Secondary: 10', 'None'),
('http://www.isecampus.nl', 'International School Eindhoven', 'Netherlands', '850 Students Nursery-12', 'International, International Baccalaureate Diploma (IB Diploma), International Baccalaureate Middle Years Programme (IBMYP), IPC', 'August - July', 1965, 'Elementary: 21, Secondary: 24', 'None'),
('http://www.isgroningen.nl', 'International School Groningen', 'Netherlands', '6-12', 'International Baccalaureate Diploma (IB Diploma), International Baccalaureate Middle Years Programme (IBMYP)', 'September - July', 1984, 'Secondary: 18', 'None'),
('http://www.isa.nl', 'International School of Amsterdam', 'Netherlands', '1,349 Students N-12', 'International, International Baccalaureate Diploma (IB Diploma), International Baccalaureate Middle Years Programme (IBMYP), International Baccalaureate Primary Years Programme (IBPYP)', 'August - June', 1964, 'Elementary: 20, Secondary: 18', 'None'),
('http://www.isob.no', 'International School of Bergen', 'Norway', '180 Students PreK-10', 'International Baccalaureate Middle Years Programme (IBMYP), International Baccalaureate Primary Years Programme (IBPYP), National', 'None', 0, 'None', 'None'),
('http://www.isstavanger.no', 'International School of Stavanger', 'Norway', '650 Students PreK-12', 'Common Ground Collaborative, International, International Baccalaureate Diploma (IB Diploma), International General Certificate of Secondary Education(IGCSE)', 'August - June', 1966, 'Elementary: 16, Secondary: 16', 'Service Learning Clubs'),
('http://www.iskonline.org', 'International School of Krakow', 'Poland', '282 Students PreK-12', 'International, International Baccalaureate Diploma (IB Diploma), United Kingdom, United States', 'August - June', 1992, 'Elementary: 20, Secondary: 18', 'Speech & Debate, Knowledge Bowl, Science, Math, Guitar, Chess, Basketball, Ballet, Soccer, Swimming'),
('http://www.aswarsaw.org', 'The American School of Warsaw', 'Poland', '989 Students PreK-12', 'International, International Baccalaureate Diploma (IB Diploma), United States', 'August - June', 1953, 'Elementary: 18, Secondary: 20', 'Animal Planet, Arts and Crafts, Chess, Book, Cooking, Hip Hop Dance, French, Knowledge Bowl, French,'),
('http://www.caislisbon.org', 'Carlucci American International School of Lisbon', 'Portugal', '660 Students PreK-12', 'International Baccalaureate Diploma (IB Diploma), United States', 'September - June', 1956, 'Elementary: 20, Secondary: 14', 'National Honor Society, Tri-M, Student Council, Community Service, Junior Model UN, Animation, Scrap'),
('http://www.stjulians.com', 'St. Julian\'s School', 'Portugal', '1,080 Students Nursery-13', 'United Kingdom, International Baccalaureate Diploma (IB Diploma)', 'September - June', 1932, 'Elementary: 19, Secondary: 19', 'Chess, Robotics, Global Issues Network'),
('http://www.aisb.ro', 'American International School of Bucharest', 'Romania', '850 Students PreK-12', 'International Baccalaureate Diploma (IB Diploma), International Baccalaureate Middle Years Programme (IBMYP), International Baccalaureate Primary Years Programme (IBPYP), United States', 'August - July', 1962, 'Elementary: 20, Secondary: 20', 'None'),
('http://www.aas.ru', 'Anglo-American School of Moscow', 'Russia', '1,207 Students PreK-12', 'International, International Baccalaureate Diploma (IB Diploma), International Baccalaureate Primary Years Programme (IBPYP), United States', 'August - June', 1949, 'Elementary: 18, Secondary: 18', 'Ultimate Frisbee, Robotics,  Cooking, MathCounts, Speech & Debate, Knowledge Bowl, Cultural Arts, Dr'),
('http://www.aas.ru/spb', 'Anglo-American School of St. Petersburg', 'Russia', '208 Students PreK-12', 'Advanced Placement (AP), International, United States', 'August - June', 1993, 'Elementary: 20, Secondary: 16', 'None'),
('http://', 'American School of Kosova', 'Serbia', '453 Students N-12', 'Advanced Placement (AP), National', 'September - August', 2003, 'Elementary: 20, Secondary: 24', 'Book/Poetry Club,Chess Club,Brain Bowl Club,Dance Club,Charity Club,Music Appreciation Club,Fashion '),
('http://', 'QSI International School of Kosovo', 'Albania', '26 Students PreK-12', 'Advanced Placement (AP), United States', 'August - June', 2015, 'Elementary: 7', 'None'),
('http://www.isb.rs', 'The International School of Belgrade', 'Serbia', '337 Students PreK-12', 'International, International Baccalaureate Diploma (IB Diploma), International Baccalaureate Middle Years Programme (IBMYP), International Baccalaureate Primary Years Programme (IBPYP)', 'August - June', 1948, 'Elementary: 12, Secondary: 15', 'Mathcounts, Knowledge Bowl, Speech & Debate'),
('http://https://www.qsi.org/slovakia/svk', 'QSI International School of Bratislava', 'Slovakia', '196 Students Nursery-12', 'Advanced Placement (AP), International Baccalaureate Diploma (IB Diploma), United States', 'August - June', 1994, 'Elementary: 12, Secondary: 12', 'Humanitarian, Habitat for Humanity, Drama, Speech and Debate, Knowledge Bowl'),
('http://www.qsi.org/slovenia/sln', 'QSI International School of Ljubljana', 'Slovenia', '150 Students PreK-12', 'Advanced Placement (AP), United States, QSI Certificate', 'August - June', 1995, 'Elementary: 14, Secondary: 12', 'Boy & Girl Scouts, Cooking, Drama, Study Group, Instrumental Music, Sports, Gardening, Arts, Crafts,'),
('None', 'None', 'None', 'None', 'None', 'None', 0, 'None', 'None'),
('http://www.asmadrid.org', 'American School of Madrid', 'Spain', '946 Students PreK-12', 'International Baccalaureate Diploma (IB Diploma), United States, Spanish Diploma Optional', 'September - June', 1961, 'Elementary: 20, Secondary: 20', 'History Bowl, Math, French, Socratic Seminar (Literature), Literary Journal & Yearbook, Cross Countr'),
('http://www.asvalencia.org', 'American School of Valencia', 'Spain', '793 Students Nursery-12', 'International Baccalaureate Diploma (IB Diploma), National, United States', 'September - June', 1980, 'Elementary: 26, Secondary: 26', 'None'),
('http://www.icsmadrid.org', 'International College Spain', 'Spain', '861 Students Nursery-12', 'International Baccalaureate Diploma (IB Diploma), International Baccalaureate Middle Years Programme (IBMYP), International Baccalaureate Primary Years Programme (IBPYP)', 'September - June', 1980, 'Elementary: 20, Secondary: 20', 'None'),
('http://www.a-s-b.com', 'The American School of Barcelona', 'Spain', '870 Students PreK-12', 'International Baccalaureate Diploma (IB Diploma), United States', 'September - June', 1962, 'Elementary: 20, Secondary: 22', 'Drama, Choir'),
('http://www.bfischool.org', 'The Benjamin Franklin International School', 'Spain', '687 Students N-12', 'International Baccalaureate Diploma (IB Diploma), National, United States', 'September - June', 1986, 'Elementary: 18, Secondary: 18', 'Model UN, Habitat for Humanity, Math Club, Film Club, Runners Club, Ambassadors Club.'),
('http://www.helsingborg.se/internationalschool', 'International School of Helsingborg', 'Sweden', '658 Students PreK-12', 'International, International Baccalaureate Diploma (IB Diploma), International Baccalaureate Middle Years Programme (IBMYP), International Baccalaureate Primary Years Programme (IBPYP)', 'August - June', 1995, 'Elementary: 22, Secondary: 20', 'Homework, Art, Language, Music & Art, Photography, Crafts, Chess, Mandarin, Science'),
('http://www.intsch.se', 'Stockholm International School', 'Sweden', '616 Students N-12', 'International, International Baccalaureate Diploma (IB Diploma), International Baccalaureate Middle Years Programme (IBMYP), IPC', 'August - June', 1951, 'Elementary: 20, Secondary: 22', 'IT, Craft & Cooking, Start-up, Gymnastics, Yoga, Taekwondo, Band'),
('http://www.brillantmont.ch', 'Brillantmont International School', 'Switzerland', '130 Students 8-13', 'Advanced Placement (AP), International General Certificate of Secondary Education(IGCSE), United Kingdom, United States', 'September - June', 1882, 'Secondary: 9', 'Charity Fundraising, Habitat for Humanity, Aerobics, Zumba, Pilates, Climbing, Cooking, Trampoline'),
('http://www.icsz.ch', 'ICS Inter-Community School Zurich', 'Switzerland', '858 Students PreK-12', 'International, International Baccalaureate Diploma (IB Diploma), International Baccalaureate Middle Years Programme (IBMYP), International Baccalaureate Primary Years Programme (IBPYP)', 'August - June', 1960, 'Elementary: 16, Secondary: 18', 'None'),
('http://www.isberne.ch', 'International School of Berne', 'Switzerland', '345 Students Nursery-12', 'International, International Baccalaureate Diploma (IB Diploma), International Baccalaureate Middle Years Programme (IBMYP), International Baccalaureate Primary Years Programme (IBPYP)', 'August - June', 1961, 'Elementary: 16, Secondary: 20', 'None'),
('http://www.ecolint.ch', 'International School of Geneva', 'Switzerland', '4,434 Students PreK-13', 'International Baccalaureate Diploma (IB Diploma), International Baccalaureate Middle Years Programme (IBMYP), International Baccalaureate Primary Years Programme (IBPYP), International General Certificate of Secondary Education(IGCSE), National, Internati', 'September - June', 1924, 'Elementary: 24, Secondary: 18', 'Many!!'),
('http://www.isl.ch', 'International School of Lausanne', 'Switzerland', '804 Students PreK-12', 'International Baccalaureate Diploma (IB Diploma), International Baccalaureate Middle Years Programme (IBMYP), International Baccalaureate Primary Years Programme (IBPYP)', 'August - June', 1962, 'Elementary: 18, Secondary: 22', 'Student Council, Excursions, String Ensemble, Stage Band, Drama, Eco, Leadership, Mathematics Compet'),
('http://www.iszl.ch', 'International School of Zug and Luzern', 'Switzerland', '1,292 Students PreK-12', 'Advanced Placement (AP), International Baccalaureate Diploma (IB Diploma), International Baccalaureate Middle Years Programme (IBMYP), International Baccalaureate Primary Years Programme (IBPYP)', 'August - June', 1961, 'Elementary: 18, Secondary: 16', 'None'),
('http://www.jfk.ch', 'John F. Kennedy International School', 'Switzerland', '75 Students PreK-10', 'United States, United Kingdom, International, International General Certificate of Secondary Education(IGCSE), International Primary Curriculum (IPC)', 'September - June', 1950, 'Elementary: 12, Secondary: 15', 'None'),
('http://www.las.ch', 'Leysin American School in Switzerland', 'Switzerland', '340 Students 7-12', 'International Baccalaureate Diploma (IB Diploma), United States', 'August - June', 1960, 'Secondary: 12', 'None'),
('http://www.switzerland.tasis.com', 'TASIS, The American School in Switzerland', 'Switzerland', '732 Students PreK-13', 'Advanced Placement (AP), International Baccalaureate Diploma (IB Diploma), United States, Core Knowledge Curriculum (elementary)', 'September - June', 1956, 'Elementary: 12, Secondary: 14', 'Peer Mediators, Peer Tutoring & Counseling, Environmental E-Club, Habitat for Humanity, Malaria Educ'),
('http://www.isbasel.ch', 'The International School of the Basel Region AG', 'Switzerland', '1,443 Students PreK-12', 'International, International Baccalaureate Diploma (IB Diploma), International Baccalaureate Middle Years Programme (IBMYP), International Baccalaureate Primary Years Programme (IBPYP)', 'August - June', 1979, 'Elementary: 18, Secondary: 17', 'None'),
('http://www.zis.ch', 'Zurich International School', 'Switzerland', '1,452 Students N-12', 'Advanced Placement (AP), Common Ground Collaborative, International Baccalaureate Diploma (IB Diploma)', 'August - June', 2001, 'Elementary: 20, Secondary: 16', 'Student Council, Model United Nations, Global Issues Network, Debate, Amnesty International, Climbin'),
('http://', 'Enka Schools', 'Turkey', '1,232 Students PreK-12', 'International Baccalaureate Diploma (IB Diploma), International Baccalaureate Middle Years Programme (IBMYP), International Baccalaureate Primary Years Programme (IBPYP), International General Certificate of Secondary Education(IGCSE), National', 'August - June', 1996, 'Elementary: 22, Secondary: 20', 'Over 50...'),
('http://www.sevamericancollege.com', 'SEV American College', 'Turkey', '550 Students 9-12', 'Advanced Placement (AP), International, International Baccalaureate Diploma (IB Diploma), National', 'September - June', 2013, 'Secondary: 24', 'Student Council, Social Service, Drama, ISTA, Sports'),
('http://www.uaa.k12.tr', 'Uskudar American Academy', 'Turkey', '840 Students 9-12', 'Advanced Placement (AP), International Baccalaureate Diploma (IB Diploma), National, United States', 'September - June', 1876, 'Secondary: 22', 'Student Association, English, French and German MUN, Art, Hiking, Chess, Photography, Turkish and En'),
('http://', 'Uskudar SEV Elementary School', 'Turkey', '990 Students PreK-8', 'National, Host Country', 'September - June', 1997, 'Elementary: 24, Secondary: 24', 'None'),
('http://www.psi.kiev.ua', 'Pechersk School International, Kyiv', 'Ukraine', '438 Students PreK-12', 'International Baccalaureate Diploma (IB Diploma), International Baccalaureate Middle Years Programme (IBMYP), International Baccalaureate Primary Years Programme (IBPYP)', 'August - June', 1995, 'Elementary: 18, Secondary: 15', 'Pay-It-Forward, Robotics, Maths Count , Destination Imagination, Student Council (Primary and Second'),
('http://https://www.qsi.org/ukraine/ukr', 'QSI Kyiv International School', 'Ukraine', '635 Students PreK-12', 'Advanced Placement (AP), International Baccalaureate Diploma (IB Diploma), United States', 'August - June', 1992, 'Elementary: 12, Secondary: 13', 'Student Council, Chess, Sewing, Humanitarian, Homework, Nature, Dance, Foreign Language, Art, Taekwo'),
('http://www.acs-schools.com/acs-cobham', 'ACS Cobham International School', 'United Kingdom', '1,482 Students Nursery-13', 'Advanced Placement (AP), International, International Baccalaureate Diploma (IB Diploma), United States', 'August - June', 1967, 'Elementary: 20, Secondary: 20', 'Student Council, Honor Society, Art, Habitat for Humanity, Peer Supporters, Animation & Science, Jun'),
('http://www.acs-schools.com', 'ACS Egham International School', 'United Kingdom', '609 Students Nursery-12', 'International Baccalaureate Diploma (IB Diploma), International Baccalaureate Middle Years Programme (IBMYP), International Baccalaureate Primary Years Programme (IBPYP), IBCC', 'August - June', 1967, 'Elementary: 16, Secondary: 16', 'Student Council, Chess, Duke of Edinburgh Award, Horseback Riding, Math, Homework, Creative Writing,'),
('http://www.acs-schools.com/acs-hillingdon', 'ACS Hillingdon International School', 'United Kingdom', '601 Students PreK-12', 'Advanced Placement (AP), International, International Baccalaureate Diploma (IB Diploma), International Baccalaureate Middle Years Programme (IBMYP), United States', 'August - June', 1978, 'Elementary: 20, Secondary: 20', 'Student Council, Homework, Drama, Jazz Music, Boy & Girl Scouts'),
('http://www.isa.aberdeen.sch.uk', 'International School of Aberdeen', 'United Kingdom', '393 Students Nursery-12', 'International, International Baccalaureate Diploma (IB Diploma), International General Certificate of Secondary Education(IGCSE)', 'August - July', 1972, 'Elementary: 18, Secondary: 18', 'Scouts, National Honor Society, EAL, Drama, Gender Equality, Circus, Home Language, Ukulele, Knittin'),
('http://www.islschools.org', 'International School of London', 'United Kingdom', '422 Students Nursery-12', 'International Baccalaureate Diploma (IB Diploma), International Baccalaureate Middle Years Programme (IBMYP), International Baccalaureate Primary Years Programme (IBPYP)', 'September - June', 1972, 'Elementary: 20, Secondary: 20', 'None'),
('http://', 'Kingham Hill School', 'United Kingdom', '302 Students 6-12', 'Advanced Placement (AP), General Certificate of Secondary Education (GCSE), International General Certificate of Secondary Education(IGCSE), National, United Kingdom, United States', 'September - July', 1886, 'Secondary: 18', 'None'),
('http://www.marymountlondon.com', 'Marymount International School', 'United Kingdom', '240 Students 6-12', 'International Baccalaureate Diploma (IB Diploma), International Baccalaureate Middle Years Programme (IBMYP), United States', 'September - June', 1955, 'Secondary: 12', 'Fab Lab, Student Council, Boarding Council, House Captains, National Honor Society, Student Newspape'),
('http://www.tasisengland.org', 'TASIS The American School in England', 'United Kingdom', '740 Students Nursery-12', 'Advanced Placement (AP), International, International Baccalaureate Diploma (IB Diploma), United States', 'August - June', 1976, 'Elementary: 15, Secondary: 15', 'Art, Chess, Computer, Conditioning, Dance, Drama, Duke of Edinburgh Award, Gardening, Sailing, Squas'),
('http://www.asl.org', 'The American School in London', 'United Kingdom', '1,343 Students PreK-12', 'Advanced Placement (AP), United States', 'August - June', 1951, 'Elementary: 18, Secondary: 16', 'Debate, Robotics, Middle East, Writers, Amnesty International, Ubuntu Education Fund, Community Serv');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
